name: CI/CD Pipeline

on:
  push:
    branches: [ '**' ]  # CI: Run on all branches
  pull_request:
    branches: [ master ]  # CI: Run on PRs targeting master  

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install dependencies
        working-directory: ./server
        run: npm ci
      
      - name: Run tests
        working-directory: ./server
        run: npm run test:ci
        env:
          NODE_ENV: test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRE: 30d
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: server/coverage/

  build:
    name: Build Docker Images
    needs: test
    runs-on: ubuntu-latest
    # Run on both PRs (to verify builds) and pushes to master
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: false
          tags: fitflow-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build Client Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: false
          tags: fitflow-client:${{ github.sha }}
          no-cache: true

  docker-hub:
    name: Push to Docker Hub
    needs: [test, build]
    runs-on: ubuntu-latest
    # CD: Only push to Docker Hub on merge to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Server
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fitflow-server:latest
            ${{ secrets.DOCKER_USERNAME }}/fitflow-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and Push Client
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/fitflow-client:latest
            ${{ secrets.DOCKER_USERNAME }}/fitflow-client:${{ github.sha }}
          no-cache: true